using System.Runtime.CompilerServices;
// <auto-generated>
// Este archivo solo debe contener atributos de nivel de ensamblado.
// No agregue ninguna definición de clase o struct, ya que podría desactivar
// la función para actualizar el archivo.
// </auto-generated>

using System;

[assembly: InternalsVisibleTo("Assembly-CSharp.Tests")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Explorables")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests1")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests2")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Tests3")]

